# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthistory',
            name='finishtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
