# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modes',
            fields=[
                ('mode', models.PositiveIntegerField(choices=[(0, b'Random'), (1, b'Least used'), (2, b'Bean Bandit')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.PositiveIntegerField()),
                ('correct', models.NullBooleanField()),
                ('choice', models.PositiveIntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('time_finished', models.DateTimeField(null=True)),
                ('score', models.PositiveIntegerField(null=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Modes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('definition', models.CharField(max_length=255)),
                ('pinyin', models.CharField(max_length=40)),
                ('rank', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=b'images/wordsets')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='wordset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.WordSet'),
        ),
        migrations.AddField(
            model_name='trial',
            name='wordset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.WordSet'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Word'),
        ),
        migrations.AddField(
            model_name='question',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Trial'),
        ),
    ]
