# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('time_finished', models.DateTimeField(null=True)),
                ('score', models.PositiveIntegerField(null=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Modes')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='wordset',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
        migrations.AddField(
            model_name='wordset',
            name='image',
            field=models.ImageField(null=True, upload_to=b'images/wordsets'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.AddField(
            model_name='trial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trial',
            name='wordset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.WordSet'),
        ),
    ]
