# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20160531_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.PositiveIntegerField()),
                ('correct', models.NullBooleanField()),
                ('choice', models.PositiveIntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('correct_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Word')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Trial')),
            ],
        ),
    ]
