# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20160602_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='time_finished',
            field=models.DateTimeField(null=True),
        ),
    ]
